<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8lt1MYK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8lt1MYK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8lt1MYK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8lt1MYK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8lt1MYK\App_KernelDevDebugContainer([
    'container.build_hash' => '8lt1MYK',
    'container.build_id' => '2dc8e48e',
    'container.build_time' => 1764337158,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8lt1MYK');
